In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
from sklearn import datasets
iris = datasets.load_iris()
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [20]:
from sklearn.decomposition import PCA
pca_iris = PCA(n_components= 2).fit_transform(iris.data)


In [21]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps= 0.3, min_samples= 6)
dbscan.fit(pca_iris)

DBSCAN(algorithm='auto', eps=0.3, leaf_size=30, metric='euclidean',
    metric_params=None, min_samples=6, n_jobs=1, p=None)

In [22]:
dbscan.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  2,  1,
        2,  2,  2, -1, -1, -1,  2, -1,  2,  2,  2,  1,  1,  2,  2, -1, -1,
        1,  2,  1, -1,  1,  2,  2,  1,  1,  2,  2,  2, -1,  2,  1,  1, -1,
        2,  2,  1,  2,  2,  2,  1,  2,  2,  2,  1,  2,  2,  1],
      dtype=int64)

In [23]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
from sklearn.metrics import silhouette_score, adjusted_rand_score
#print(silhouette_score(iris.target, dbscan.labels_))
#print(silhouette_score(dbscan.labels_,iris.target))
print(adjusted_rand_score(dbscan.labels_,iris.target))

0.584245005697512


In [25]:
print(adjusted_rand_score(dbscan.labels_[dbscan.labels_>-1],iris.target[dbscan.labels_>-1]))

0.7371657536975863
